<a href="https://colab.research.google.com/github/rafio1020/phitron-ai-ml/blob/main/module_9_NumPy_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.random.randint(1,100,size=(10,5)) # sample/row=10, features/col=5

In [ ]:
arr.shape

(10, 5)

In [ ]:
b = arr.reshape(5,10)

b.shape
b.ndim
b

array([[28, 17, 43, 37, 51, 56, 24, 72, 97, 72],
       [68, 65, 78, 41, 58, 35, 84,  9, 45, 10],
       [56,  8, 59, 78, 94, 23, 56, 22, 95, 79],
       [37, 77, 39,  8, 41, 74, 47, 94,  1, 62],
       [54, 24, 86, 61, 29, 57, 66, 40, 16, 25]])

In [ ]:
flatten = b.flatten()

print(flatten.ndim)
flatten

column_wise_flattening = np.ravel(b,order = 'F') # F for Colwise and C for Rowwise
print(column_wise_flattening)

1
[28 68 56 37 54 17 65  8 77 24 43 78 59 39 86 37 41 78  8 61 51 58 94 41
 29 56 35 23 74 57 24 84 56 47 66 72  9 22 94 40 97 45 95  1 16 72 10 79
 62 25]


In [ ]:
a = np.random.randint(1,10,size=(2,3))
b = np.random.randint(20,30,size=(2,3))

Concatenate

In [ ]:
con_row = np.concatenate([a,b],axis=0)
print(con_row)
con_col = np.concatenate([a,b],axis=1)
print(con_col)

[[ 4  7  5]
 [ 8  2  6]
 [26 29 21]
 [25 21 23]]
[[ 4  7  5 26 29 21]
 [ 8  2  6 25 21 23]]


In [ ]:
# error
x = np.random.randint(1,10,size=(2,3))
y = np.random.randint(1,10,size=(1,3))

r = np.concatenate((x,y),axis=0)
print(r)
q = np.concatenate((x,y),axis=1)
print(q)

# For Rowwise concat we need make the col same
# For Colwise concat we need make the row same

[[7 5 6]
 [6 2 5]
 [6 1 5]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

Transpose

In [ ]:
mat = np.array([
    [10,20,30],
    [40,50,60]
])

transpose = mat.T
print(transpose)

[[10 40]
 [20 50]
 [30 60]]


Array Split

In [ ]:
a = np.random.randint(1,10,size=(10,))
print(a)
splitted_array = np.array_split(a,3)
print(splitted_array)
splitted_array = np.split(a,3)
print(splitted_array)
# split function can only be used in an equal division


[5 8 3 4 8 2 8 7 5 7]
[array([5, 8, 3, 4]), array([8, 2, 8]), array([7, 5, 7])]


ValueError: array split does not result in an equal division

In [ ]:
splitted_array = np.split(a,5)
print(splitted_array)

[array([5, 8]), array([3, 4]), array([8, 2]), array([8, 7]), array([5, 7])]


Arithmatic Operator and Mathematical Functions

In [ ]:
#faster for vectorization
x = np.array([10,20,30,50])
y = np.array([2,4,5,6])

add = x+y
print(add) # if list output be like concat [10,20,30,50,2,4,5,6]

sub = x-y
print(sub)

mul = x*y
print(mul)

div = x/y
print(div)

remainder = x%y
print(remainder)

[12 24 35 56]
[ 8 16 25 44]
[ 20  80 150 300]
[5.         5.         6.         8.33333333]
[0 0 0 2]


Mathematical Functions

In [ ]:
# trigonometry
#sin cos tan takes the value in radian
sin_val = np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

deg_con = np.rad2deg(x) # radian to degree
print(deg_con)

#deg2rad

[-0.54402111  0.91294525 -0.98803162 -0.26237485]
[-0.83907153  0.40808206  0.15425145  0.96496603]
[ 572.95779513 1145.91559026 1718.87338539 2864.78897565]


In [ ]:
# log
x = np.array([1,10,100,1000])
base_10_log_val = np.log10(x)
print(base_10_log_val)

# log base 2
base_2_log_val = np.log2(x)
print(base_2_log_val)


[0. 1. 2. 3.]
[0.         3.32192809 6.64385619 9.96578428]


In [ ]:
# different
sum = np.sum(x)
cumulative_sum = np.cumsum(x)
print(sum,cumulative_sum)

1111 [   1   11  111 1111]


Logical Function


In [ ]:
# Comparison
x = np.array([10,8,16,100])
y = np.array([2,10,5,6])
greater_than = x>y
print(greater_than)

# like this determine others like <,==,<=,>=,!=
# all() --> Checks if all are true
# any() --> checks if one if them are true

print(np.all(x>y))
print(np.any(x>y))

[ True False  True  True]
False
True


Sorting

In [ ]:
#inplace
x = np.array([10,8,16,100])
z = x.copy()
print(z)
z.sort()
print(z)

#copy sorting
sort_arr = np.sort(x)
print(sort_arr)


[ 10   8  16 100]
[  8  10  16 100]
[  8  10  16 100]


In [ ]:
# 2nd array sorting
mat = np.array([
    [20,30,30],
    [10,5,60]
])

# horizon axis = 1
hor_sort = np.sort(mat,axis=1)
print(hor_sort)

# vertical axis = 0
ver_sort = np.sort(mat,axis=0)
print(ver_sort)

[[20 30 30]
 [ 5 10 60]]
[[10  5 30]
 [20 30 60]]


Searching

In [ ]:
print(x)

[ 10   8  16 100]


In [ ]:
# np.where(condition) ; returns index

index = np.where(x==16)
print(index)

index = np.where(x>8)
print(index)

# np.where(condition,x,y) if true x, otherwise replace with y; returns the array not the index
arr = np.where(x>8,x,0)
print(arr)

(array([2]),)
(array([0, 2, 3]),)
[ 10   0  16 100]


In [ ]:
print(mat)

index = np.where(mat>20)
print(index)

arr = np.where(mat>20,mat,0)
print(arr)

[[20 30 30]
 [10  5 60]]
(array([0, 0, 1]), array([1, 2, 2]))
[[ 0 30 30]
 [ 0  0 60]]


In [ ]:
max_val = np.argmax(x)
min_val = np.argmin(x)
print(x)
print(max_val) #index 0,1,2,3,....
print(min_val)

[ 10   8  16 100]
3
1


Counting in ndarray

In [ ]:
a = np.random.randint(1,100,size=(100))
a


array([64, 42, 91, 81, 41, 34, 51, 19, 45, 67, 17, 85, 73, 24, 20, 13, 90,
       38, 16, 10, 64, 92, 90, 70,  6, 68, 28, 27,  4, 31, 58, 54, 38, 58,
       91, 60, 60, 53, 86, 51, 16, 65, 48, 51, 19, 17, 93, 46, 25, 33, 84,
       14, 46, 45, 86, 83, 78, 16, 19, 31, 41, 21, 86, 22, 63, 33, 47, 47,
       20, 45, 42, 88, 29, 24, 25, 86, 60, 32, 66, 42, 91, 33, 70, 57, 99,
       59, 29, 24, 13,  8, 38, 92, 57, 53, 20, 68, 40, 28, 82, 13])

In [ ]:
value_greater_than_60 = np.count_nonzero(a>60)
print(value_greater_than_60)

31


In [ ]:
unique_val,count= np.unique(a,return_counts = True)
print(unique_val)
print(count)

[ 4  6  8 10 13 14 16 17 19 20 21 22 24 25 27 28 29 31 32 33 34 38 40 41
 42 45 46 47 48 51 53 54 57 58 59 60 63 64 65 66 67 68 70 73 78 81 82 83
 84 85 86 88 90 91 92 93 99]
[1 1 1 1 3 1 3 2 3 3 1 1 3 2 1 2 2 2 1 3 1 3 1 2 3 3 2 2 1 3 2 1 2 2 1 3 1
 2 1 1 1 2 2 1 1 1 1 1 1 1 4 1 2 3 2 1 1]


Statistical Analysis

In [44]:
# dataset load
data = np.genfromtxt('sample_data/student_scores.csv', delimiter=',', skip_header=1)
print(data)


[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [49]:
math_marks = data[::,:1]
print(math_marks.T)

max_math_marks = np.max(math_marks)
print(max_math_marks)

min_math_marks = np.min(math_marks)
print(min_math_marks)

average_math_marks = np.mean(math_marks)
print(average_math_marks)

median_math_marks = np.median(math_marks)
print(median_math_marks)

# standard deviation
std_math_marks = np.std(math_marks)
print(std_math_marks)

[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.5
13.788672887555204


In [50]:
# Correlation
study_hours = np.array([2,4,5,6])
exam_scores = np.array([40,50,60,80])

data = np.array([study_hours,exam_scores])
print(data)

correlation = np.corrcoef(data)
print(correlation)

[[ 2  4  5  6]
 [40 50 60 80]]
[[1.         0.94285714]
 [0.94285714 1.        ]]


Linear Algebra


In [58]:
# matrics multiplication

A = np.array([
    [4,5,6],
    [7,8,9],
    [1,2,3]
])

B = np.array([
    [1,2,3],
    [14,9,6],
    [7,8,9]
])

dot_product = np.dot(A,B)
print(dot_product)

# trace
print(np.trace(B)) # gets the sum of the diagonal elements

# determinant
print(np.linalg.det(B))

# rank
rank_of_B = np.linalg.matrix_rank(B)
print(rank_of_B)

[[116 101  96]
 [182 158 150]
 [ 50  44  42]]
19
12.00000000000001
3


In [59]:
A = np.array([
    [1,2],
    [3,4]
])
B = np.array([
    [5,6],
    [7,8]
])
print(np.dot(A,B))

[[19 22]
 [43 50]]
