<a href="https://colab.research.google.com/github/rafio1020/phitron-ai-ml/blob/main/module_8_NumPy_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
arr = [1,3,4]
print(arr*5)
for x in arr:
  x*=5
print(arr)

[1, 3, 4, 1, 3, 4, 1, 3, 4, 1, 3, 4, 1, 3, 4]
[1, 3, 4]


In [ ]:
# Better way as CPU less utilized
import numpy as np
arr1 = np.array([4,5,6])
arr1 = arr1*5
print(arr1)

[20 25 30]


ndarray

In [ ]:
import numpy as np

# 1d array
arr1 = np.array([1,2,3,4,5])
print(type(arr1))
print(arr1.ndim)

# 2d array
arr2 = np.array([[1,2,3],  # row1
                 [4,5,6]]) # row2
print(arr2.ndim)

# 3d array
arr3 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,2,9],
        [8,5,3]
    ],
    [
        [5,6,3],
        [1,2,6]
    ]
])
print(arr3.ndim)

<class 'numpy.ndarray'>
1
2
3


Array Attributes

In [ ]:
# dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

# shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

# data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

# size
print(arr1.size)
print(arr2.size)
print(arr3.size)

1
2
3
(5,)
(2, 3)
(3, 2, 3)
int64
int64
int64
5
6
18


ndarray data type

In [ ]:
arr = np.array([1,2,3])
print(arr.dtype)

arr = np.array([1.3,45.4,2.4])
print(arr.dtype)

int64
float64


In [ ]:
arr = np.array([1,2,3.4])
# upcasting
print(arr.dtype)

# upcasted to string
arr = np.array([1,2,3.4,"ss"])
print(arr.dtype)

float64
<U32


Selecting a data type for an array

In [ ]:
arr = np.array([1,2,300])
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr.dtype)

arr = np.array([1,2,True,300,"hello"])
print(arr.dtype)

int64
int16
<U21


ndarray creation from existing data

In [ ]:
# list
list1 = [10,20,30,40.5]
arr = np.array(list1, np.int32)
print(arr)
print(type(arr))
print(arr.dtype)

mixed_list = [10,True,'Hello',10.5]
arr = np.array(mixed_list)
print(arr)
print(type(arr))
print(arr.dtype)

matrix = [
    [1,2,3],
    [4,5,7]
]
arr = np.array(matrix)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[10 20 30 40]
<class 'numpy.ndarray'>
int32
['10' 'True' 'Hello' '10.5']
<class 'numpy.ndarray'>
<U32
[[1 2 3]
 [4 5 7]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [ ]:
# tuple
tpl = (1,2,3)
arr = np.array(tpl)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1


In [ ]:
# set
set1 = {1,2,3}
arr = np.array(list(set1))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1


In [ ]:
# disctionary
dict1 = {"a":1, "b":2, "c":3}
print(type(dict1))
keys = dict1.keys()
values = dict1.values()
items = dict1.items()
print(keys, values, items)

<class 'dict'>
dict_keys(['a', 'b', 'c']) dict_values([1, 2, 3]) dict_items([('a', 1), ('b', 2), ('c', 3)])


In [ ]:
# keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [ ]:
# values to ndarray
arr = np.array(list(values))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1
3


In [ ]:
# items to ndarray
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['a' '1']
 ['b' '2']
 ['c' '3']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6
